### ISSUE TITLE
widest_on_top not working in plot.eval_sensitivity

### ISSUE THREAD

**Issue by jafelds** [pierucci/heemod#93] opened 2016-07-20 21:11 UTC
res <- run_sensitivity(model = res_mod,sensitivity = se)
plot(res,model="BVA",type="diff",widest_on_top = TRUE
![rplot](https://cloud.githubusercontent.com/assets/6664302/17003233/f038adce-4e9c-11e6-8794-c60c36f31565.png)
)

**Comment by MattWiener** [comment] 2016-07-29 06:15
Hi, Jafelds.    Sorry for the late reply - I've been on vacation - and thanks for showing this.   Can you specify the entire model here so I can reproduce the error?   I don't recognize your model, and when I try it with the models I have, it works.

I've run using the [AIDS treatment model](https://cran.r-project.org/web/packages/heemod/vignettes/sensitivity.html) in one of the vignettes, using the [hip replacement model](https://cran.r-project.org/web/packages/heemod/vignettes/non-homogeneous.html) from another, and some other models not in the vignettes, and everything seems to work.

For example, starting with an empty environment, I loaded heemod and then pasted in the AIDS model and the sensitivity parameters directly from the vignette above and the couple of commands from the [sensitivity analysis vignette](https://cran.r-project.org/web/packages/heemod/vignettes/sensitivity.html), and then ran using the command from the sensitivity analysis vignette.    Here are the sensitivity plots, first without and then with widest_on_top = TRUE:
![image](https://cloud.githubusercontent.com/assets/7340969/17239297/491d1980-5563-11e6-8cc8-6d47a35647b5.png)
![image](https://cloud.githubusercontent.com/assets/7340969/17239303/57a82af8-5563-11e6-89cc-c961b689e4a1.png)

Finally, it looks like your plot does not have the new title added along with the widest_on_top argument, so it's possible you're running an old version.

Regards,
Matt Wiener

**Comment by pierucci** [comment] 2016-08-14 16:41
@jafelds is the problem fixed with the new version?

**Closed** 2016-08-14 16:41 UTC
